### ISSUE TITLE
關於psd檔案的開啟工具

### ISSUE THREAD

**Issue by Andy5066** [MuteApo/AzurLaneTachieHelper#8]
其實從去年的舊版本我就有這個疑問，那就是本工具匯出的psd檔案用什麼軟體開啟比較好呢？
我的需求很簡單，只有匯出png並將背景自動轉成白色

由於我沒有購買photoshop，因此我嘗試了幾種免費軟體
1. HoneyView：我一般開啟圖片的軟體，但開啟後一片黑色
2. XNVIEW：同上，開啟後一片黑色
3. Pixlr X：大部分情況可以正常打開，但有時會無法讀取到部分圖層(比如最新的dipulaikesi_2.psd，讀不到背景，但工具本身是正常的)
4. GIMP：目前看起來最好的軟體，上述dipulaikesi_2.psd可以正常打開編輯，但匯出成png時速度很慢，且沒有背景自動轉白色的功能(Pixlr X可以)

總之，請問你有什麼推薦的嗎？謝謝！

**Comment by MuteApo** [comment]
No plan to make possible non-photoshop editing yet. Feel free to PR if any implementation is available for the software mentioned.

**Comment by Andy5066** [comment]
不好意思，我完全不會繪圖之類的技能，所以對類似的工具也不太清楚，沒辦法提供什麼建議

至於使用本工具匯出psd後會是黑色的，我在使用phototea的時候發現了一些東西
1. 這是photopea開啟dipulaikesi.psd後的畫面，可以看到都是點陣圖
![圖片](https://github.com/user-attachments/assets/ec4e491b-8579-4a21-99b4-538979bd02ea)
2. 但是如果我刪除同一個圖層的光柵遮罩【兩次】，他就會正確的顯示
> 比如第一次刪除最下面圖層的光柵遮罩，此時還沒有變化
![圖片](https://github.com/user-attachments/assets/4f5cae3d-3bc7-46ad-aac9-871e5a68ef15)
> 但第二次刪除後，該圖層就會正常顯示了
![圖片](https://github.com/user-attachments/assets/f04441de-f713-4ec7-a3e3-aa1f4949fd0a)
![圖片](https://github.com/user-attachments/assets/84fc1417-ddfd-46e5-8594-7eda04e58b21)
4. 所以如果我重複上面的步驟把所有圖層的光柵遮罩刪除，那麼psd就可以普通的顯示出來
![圖片](https://github.com/user-attachments/assets/1e82eefc-81c3-42bc-958c-0f7fd11a4cf9)
5. 不知道原因是什麼，只能打在這邊給你參考，抱歉

至於未來的使用我應該會改用GIMP看看，目前看起來這個軟體可以直接開啟本工具匯出的psd沒有問題
