### ISSUE TITLE
How can I install this program？

### ISSUE THREAD

**Issue by Arthur1588** [MuteApo/AzurLaneTachieHelper#9]
Sorry to bother,I know this is a stupid question but I a fresh in Python works,I really want to know how I can change the whole py files into exe and open it.

**Comment by MuteApo** [comment]
Pre-built exe is deployed in actions (find it on the top menu bar of this repo), no need to learn python anyway.

**Comment by Arthur1588** [comment]
I don't know what to say, but please accept my gratitude,I found it.
